In [3]:
import pandas as pd

df = pd.read_csv('insurance.csv')
display(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [6]:
import statsmodels.api as sm

y = df['charges']
x = df[['age', 'bmi', 'children']]

x = sm.add_constant(x)
display(x.head())

model = sm.OLS(y, x).fit()
display(model.summary())

   const  age     bmi  children
0    1.0   19  27.900         0
1    1.0   18  33.770         1
2    1.0   28  33.000         3
3    1.0   33  22.705         0
4    1.0   32  28.880         0

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.120
Model:                            OLS   Adj. R-squared:                  0.118
Method:                 Least Squares   F-statistic:                     60.69
Date:                Tue, 10 Feb 2026   Prob (F-statistic):           8.80e-37
Time:                        14:39:09   Log-Likelihood:                -14392.
No. Observations:                1338   AIC:                         2.879e+04
Df Residuals:                    1334   BIC:                         2.881e+04
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -6916.2433   1757.480     -3.935      0.000   -1.04e+04   -3468.518
age          239.9945     22.289     10.767      0.000     196.269     283.720
bmi          332.0834     51.310      6.472      0.000     231.425     432.741
children     542.8647    258.241      2.102      0.036      36.261    1049.468
==============================================================================
Omnibus:                      325.395   Durbin-Watson:                   2.012
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              603.372
Skew:                           1.520   Prob(JB):                    9.54e-132
Kurtosis:                       4.255   Cond. No.                         290.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
df_dummy = df.copy()

y = df_dummy['charges']
x = df_dummy.drop(columns=['charges']).assign(const=1)
x = pd.get_dummies(x, columns=['region', 'sex', 'smoker'], drop_first=True)
x[x.select_dtypes(bool).columns] = x[x.select_dtypes(bool).columns].astype(int)

model = sm.OLS(y, x).fit()
display(model.summary())

x.head()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     500.8
Date:                Tue, 10 Feb 2026   Prob (F-statistic):               0.00
Time:                        14:47:02   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1329   BIC:                         2.716e+04
Df Model:                           8
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
age                256.8564     11.899     21.587      0.000     233.514     280.199
bmi                339.1935     28.599     11.860      0.000     283.088     395.298
children           475.5005    137.804      3.451      0.001     205.163     745.838
const            -1.194e+04    987.819    -12.086      0.000   -1.39e+04      -1e+04
region_northwest  -352.9639    476.276     -0.741      0.459   -1287.298     581.370
region_southeast -1035.0220    478.692     -2.162      0.031   -1974.097     -95.947
region_southwest  -960.0510    477.933     -2.009      0.045   -1897.636     -22.466
sex_male          -131.3144    332.945     -0.394      0.693    -784.470     521.842
smoker_yes        2.385e+04    413.153     57.723      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      300.366   Durbin-Watson:                   2.088
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              718.887
Skew:                           1.211   Prob(JB):                    7.86e-157
Kurtosis:                       5.651   Cond. No.                         311.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

,age,bmi,children,const,region_northwest,region_southeast,region_southwest,sex_male,smoker_yes
0,19,27.900,0,1,0,0,1,0,1
1,18,33.770,1,1,0,1,0,1,0
2,28,33.000,3,1,0,1,0,1,0
3,33,22.705,0,1,1,0,0,1,0
4,32,28.880,0,1,1,0,0,1,0